server:
  timeout: 1800

spring:
  profiles:
    active: @spring.active@
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

mybatis-plus:
  typeAliasesPackage: com.deepspc.stage.**.entity
  mapper-locations: classpath*:com/deepspc/stage/**/mapping/*.xml
