spring:
  profiles:
    active: @spring.active@
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

mybatis-plus:
  typeAliasesPackage: com.deepspc.stage.manager.modular.*.entity
  mapper-locations: classpath*:com/deepspc/manager/**/mapping/*.xml
