spring:
  datasource:
    druid:
      primary:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.35:3306/ec_test?characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: deepspc
        password: deepspc
      second:
        enabled: true
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.35:3306/oa_test?characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: dlsoa_test
        password: dlsOaTest2020