server:
  tokentimeout: 1800      #token超时时间(单位秒)
  tokenlive: 3600000     #token有效期(单位毫秒)
  attachment-path: D:/esmanager/

spring:
  profiles:
    active: @spring.active@
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    cache: false
  template:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

stage:
  appname: 电商后台管理系统
  shiro:
    anon-request: /css/**,/images/**,/js/**,/plugins/**,/sys/refreshCryptoKey,/checkValid,/loadCaptcha
    access-type: integrated

mybatis-plus:
  typeAliasesPackage: com.deepspc.stage.**.entity
  mapper-locations: classpath*:com/deepspc/stage/**/mapping/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
