spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.191.121:3306/ec_test?characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: deepspc
    password: deepspc

